/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_tokobuku;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arumia
 */
public class Kasir extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    public Kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        labelJam1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHargaBarang = new javax.swing.JTextField();
        txtIdBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        buttonClear1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_barang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        buttonDelete1 = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();
        buttonPrint = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        labelJam = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        labelJam1.setForeground(new java.awt.Color(255, 255, 102));
        labelJam1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJam1.setText("Jam :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Data Barang"));
        jPanel2.setLayout(null);

        jLabel2.setText("ID Barang");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 60, 70, 30);

        jLabel3.setText("Harga Barang");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 140, 80, 30);

        jLabel4.setText("Nama Barang");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 100, 80, 30);

        txtHargaBarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaBarangActionPerformed(evt);
            }
        });
        jPanel2.add(txtHargaBarang);
        txtHargaBarang.setBounds(110, 140, 170, 30);

        txtIdBarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtIdBarang);
        txtIdBarang.setBounds(110, 60, 170, 30);

        txtNamaBarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtNamaBarang);
        txtNamaBarang.setBounds(110, 100, 170, 30);

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSave);
        buttonSave.setBounds(60, 210, 80, 30);

        buttonClear1.setText("Clear");
        buttonClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClear1ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClear1);
        buttonClear1.setBounds(150, 210, 80, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 160, 300, 310);

        tb_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_barang", "nama_barang", "harga_barang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_barang);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(340, 230, 452, 230);

        jPanel3.setLayout(null);

        buttonDelete1.setText("Delete");
        buttonDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelete1ActionPerformed(evt);
            }
        });
        jPanel3.add(buttonDelete1);
        buttonDelete1.setBounds(20, 20, 80, 30);

        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(buttonRefresh);
        buttonRefresh.setBounds(120, 20, 80, 30);

        buttonPrint.setText("Print");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });
        jPanel3.add(buttonPrint);
        buttonPrint.setBounds(220, 20, 80, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(390, 150, 360, 70);

        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Toko Buku dan Alat Tulis");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 30, 820, 30);

        labelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTanggal.setText("Tanggal :");
        jPanel4.add(labelTanggal);
        labelTanggal.setBounds(700, 50, 80, 30);

        labelJam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelJam.setText("Jam :");
        jPanel4.add(labelJam);
        labelJam.setBounds(720, 70, 60, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 830, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 490);

        setBounds(0, 0, 844, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        
        if ("".equals(txtIdBarang.getText()) || "".equals(txtNamaBarang.getText()) || "".equals(txtHargaBarang.getText()))
        {
            JOptionPane.showMessageDialog(this, "Lengkapi Data Barang", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        String SQL = "INSERT INTO tb_barang (id_barang,nama_barang,harga_barang)"
                + "VALUES('"+txtIdBarang.getText()+"','"+txtNamaBarang.getText()+"','"+txtHargaBarang.getText()+"')";
        
        int status = KoneksiDB.execute(SQL);
        if(status == 1)
        {
            JOptionPane.showMessageDialog(this, "Data Barang berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Data Barang gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void txtHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaBarangActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        
        selectData();
         
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        
        MessageFormat header = new MessageFormat("Toko Buku dan Alat Tulis "
              + "One Piece");
      MessageFormat footer = new MessageFormat("Page {0,number,integer}  ");
      
      try{
          tb_barang.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, 
                  true, null);
          }
      catch(java.awt.print.PrinterException e)
      {
          System.err.format("Cannot print %s%n", e.getMessage());
      }      
        
    }//GEN-LAST:event_buttonPrintActionPerformed

    private void buttonDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelete1ActionPerformed
        int baris = tb_barang.getSelectedRow();
        if(baris != -1)
        {   String id_barang = tb_barang.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_barang WHERE id_barang='"+id_barang+"'";
            int status = KoneksiDB.execute(SQL);
            
            if (status == 1)
            { JOptionPane.showMessageDialog(this, "Data berhasil dihapus",
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);}
            else
            { JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal", 
                    JOptionPane.WARNING_MESSAGE);}}
        else
        { JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih "
                    + "Dahulu","Error",JOptionPane.WARNING_MESSAGE);}
        
    }//GEN-LAST:event_buttonDelete1ActionPerformed

    private void buttonClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClear1ActionPerformed
        txtIdBarang.setText("");
        txtNamaBarang.setText("");
        txtHargaBarang.setText("");
    }//GEN-LAST:event_buttonClear1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear1;
    private javax.swing.JButton buttonDelete1;
    private javax.swing.JButton buttonPrint;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelJam;
    private javax.swing.JLabel labelJam1;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JTable tb_barang;
    private javax.swing.JTextField txtHargaBarang;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtNamaBarang;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        
          String kolom[] = {"id_barang","nama_barang","harga_barang"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM tb_barang";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try{while(rs.next())
            {  String id_barang = rs.getString(1);
               String nama_barang = rs.getString(2);
               String harga_barang = rs.getString(3);
      String data[] = {id_barang,nama_barang,harga_barang};
               dtm.addRow(data);}}
        
        catch(SQLException ex)
        {Logger.getLogger(Kasir.class.getName()).log(Level.SEVERE, null, ex);}
        tb_barang.setModel(dtm);
        
       }
    
    public void setTanggal()
    {
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd/MM//yyy");
        labelTanggal.setText(kal.format(skrg));
    } 
    
    public void setJam()
    {
        ActionListener taskPerformer = new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                
                String jam = Integer.toString(nilai_jam);
                String menit = Integer.toString(nilai_menit);
                String detik = Integer.toString(nilai_detik);
                labelJam.setText("Jam " + jam + ":" + menit + ":" + detik);
            }
        };
         new Timer(100, taskPerformer).start();       
    }
    
    
}
